version: '3.3'

services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql:8
    env_file: env/db.env
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql

  web:
    build: .
    restart: always
    command: python /code/manage.py runserver 0.0.0.0:8000
    env_file: .env
    environment:
      - DB_SERVER=${DB_SERVER}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - mysql
    links:
      - mysql
    entrypoint: /entrypoint.sh

  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - mysql
      - web
    links:
      - mysql
      - web
    entrypoint: /telegram_bot.sh
    

volumes:
  mysql: